---
- name: Updating cache and installing systemd and unzip
  apt:
    update_cache: "yes"
    name: ['unzip', 'systemd']
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5

- name: Creating user for prometheus
  user:
    name: "{{ user_name }}"
    shell: /bin/false

- name: Setting internal variables for convenience
  set_fact:
    prometheus_url: "{{ base_download_url }}/v{{ version }}/{{ prom_tar_file }}"

- name: Checking Prometheus Binary
  stat:
    path: "{{ prometheus_binary_path }}/prometheus"
  register: check_prom_binary

- name: Downloading the binary file for Prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "{{ unarchive_destination }}"
    remote_src: "yes"
  when: check_prom_binary.stat.exists == false

- name: Checking prometheus file
  ansible.builtin.stat:
    path: "{{ unarchive_destination }}prometheus-{{ version }}.linux-amd64/prometheus"
  register: check_unarchive_file_present

- name: Move the binary executable file
  copy:
    src: "{{ unarchive_destination }}prometheus-{{ version }}.linux-{{ system_arch }}/prometheus"
    dest: "{{ prometheus_binary_path }}"
    mode: 0555
    remote_src: "yes"
  when: check_unarchive_file_present.stat.exists == true

- name: Create directory for Prometheus Configuration and for Data dump
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
  with_items:
    - "{{ prometheus_config_path }}"
    - "{{ storage_path }}"

- name: Adding Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
  notify:
    - restart_prometheus_service

- name: Copy Service for Prometheus
  template:
    src: prometheus.service.j2
    dest: "{{ service_file_dest }}/prometheus.service"
    owner: root
    group: root
  notify:
    - reload_prometheus_service
    - restart_prometheus_service
