---
- name: Checking Prometheus hosts are defined or not
  fail:
    msg: "Playbook failed due to missing or empty required group 'agents'"
  when: groups['agents'] is not defined or groups['agents']|length == 0 and agent_discovery == "yes"
