---
- name: Creating user for Prometheus
  user:
    name: "{{ user_name }}"
    shell: /bin/false

- name: Setting internal variables for convinience
  set_fact:
    prometheus_url: "{{ base_download_url }}/v{{ version }}/{{ prom_tar_file }}"

- name: Download and install unzip
  yum:
    name: ['unzip', 'libselinux-python']
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5

- name: Installing Systemd on Centos
  yum:
    name: systemd
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5
  when:
    ansible_distribution_major_version == "7"

- name: Copy init script of Prometheus for Centos 6
  template:
    src: prometheus.init.j2
    dest: /etc/init.d/prometheus
    mode: 0555
  when:
    ansible_distribution_major_version == "6"

- name: Checking Prometheus Binary
  stat:
    path: "{{ prometheus_binary_path }}/prometheus"
  register: check_prom_binary

- name: Downloading the binary file for Prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "{{ unarchive_destination }}"
    remote_src: "yes"
  when: check_prom_binary.stat.exists == false

- name: Checking prometheus files
  ansible.builtin.stat:
    path: "{{ unarchive_destination }}prometheus-{{ version }}.linux-amd64/prometheus"
  register: check_unarchive_file_present

- name: Move the binary executable file
  copy:
    src: "{{ unarchive_destination }}prometheus-{{ version }}.linux-{{ system_arch }}/prometheus"
    dest: "{{ prometheus_binary_path }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0550
    remote_src: "yes"
  when: check_unarchive_file_present.stat.exists == true

- name: Create directory for Prometheus Configuration and for Data dump
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    recurse: yes
  with_items:
    - "{{ prometheus_config_path }}"
    - "{{ storage_path }}"

- name: Adding Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
  notify:
    - restart_prometheus_service

- name: Copy Service for Prometheus
  template:
    src: prometheus.service.j2
    dest: "{{ service_file_dest }}/prometheus.service"
  notify:
    - reload_prometheus_service
    - restart_prometheus_service
  when:
    ansible_distribution_major_version == "7"

- name: Create Logs Directory
  file:
    path: /var/log/prometheus
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Restarting the init prometheus service
  service:
    name: prometheus
    state: started
  when:
    ansible_distribution_major_version == "6"
